### PR TITLE
Improvements to EuiTableOfRecords documentation

### PR DESCRIPTION
**Pull request by cjcenizal**
This PR makes the following changes:

* Adds ability to toggle on and off different features of the "Multiple record actions" table example
* Renames `ValueRenderers` to `EuiValueRenderers`
* Adds an example that demonstrates the different `dataType`s in a single table
* Some general code cleanup

I'd also like to make these changes:

* Cull the footer within `EuiTableOfRecords` based on the lack of pagination data in either `config` or `criteria` (currently it only drops the footer if `criteria` is missing)
* ~~Rename the `dataType` property to `renderType` to clarify that this is a rendering concern~~
* Rename the `key` property on the column config object to `id` because it was pretty unexpected to me that `EuiTableOfRecords` would consume `key` (I expected it to be treated as a regular React `key`, which can be named anything or even left out). I think `id` will make it clearer that it has a special role. `EuiTableOfRecords` can still pass it to the columns it as a `key` prop internally.

@uboness Thoughts? Doubts? Applause and adulation? 😄

### CODE REVIEW

**Comment by cjcenizal** [comment]
@uboness I made the changes we talked about and this is now ready for another look.

**Comment by uboness** [comment]
@cjcenizal I've been thinking... maybe instead of `id` we should call it `property` or `field`, because this is what it is. `id` feels like something that must be set on every column, but it's not really the case... the `id` (used to be `key`) is used to identify the field to extract and show from the record for that particular column... columns without ids are "computed" columns (potentially computed out of multiple fields). wdyt?

**Comment by cjcenizal** [comment]
@uboness That's a good point, I like it! Let's use `field`. I'll change this on Monday.

**Comment by cjcenizal** [comment]
@uboness Done, ready for another look.

**Comment by uboness** [comment]
LGTM

**Pull request merged**
